"""Ask Oriflux (issue #34, PRD §6): natural language → the typed query.

The model receives the registry vocabulary and must emit a QueryRequest
JSON — the SAME contract as dashboard/REST/MCP. Hallucinations die at
schema validation; one repair round feeds the validation error back;
past that we raise instead of guessing. SQL is never generated by a
model anywhere in this file or this product.
"""

import json
import re
from datetime import UTC, datetime
from typing import Protocol

from pydantic import ValidationError

from oriflux.query.models import QueryRequest
from oriflux.query.registry import DIMENSIONS, GRANULARITY_SQL, METRICS


class AskCompilationError(Exception):
    """The model could not produce a valid QueryRequest — we never guess."""


class ChatGateway(Protocol):
    async def chat(
        self,
        org_id: str,
        *,
        feature: str,
        messages: list[dict[str, str]],
        temperature: float = 0.2,
    ) -> str: ...


def registry_vocabulary() -> str:
    """The ONLY vocabulary the model may use — generated from the registry
    so it can never drift from what actually validates."""
    metrics = ", ".join(sorted(METRICS))
    events_dims = ", ".join(
        sorted(name for name, spec in DIMENSIONS.items() if "events" in spec.sources)
    )
    api_dims = ", ".join(
        sorted(name for name, spec in DIMENSIONS.items() if "api" in spec.sources)
    )
    granularities = ", ".join(GRANULARITY_SQL)
    return (
        f"metrics: {metrics}\n"
        f"dimensions (web/events metrics): {events_dims}\n"
        f"dimensions (api_* metrics): {api_dims}\n"
        f"filter ops: eq, neq, in, prefix\n"
        f"granularities: {granularities}\n"
    )


_SYSTEM = (
    "You compile analytics questions (French, English or Spanish) into ONE "
    "JSON object matching this schema:\n"
    '{{"metric": str, "dimensions": [str], "filters": [{{"dimension": str, '
    '"op": str, "value": str|[str]}}], "granularity": str|null, '
    '"period": {{"start": ISO8601, "end": ISO8601}}, '
    '"compare_to": "previous_period"|"previous_year"|null}}\n\n'
    "Rules:\n"
    "- Use ONLY names from this vocabulary (anything else fails validation):\n"
    "{vocabulary}\n"
    '- Resolve relative dates against now = {now} (UTC). "this month" = '
    "month start to now.\n"
    "- Output the JSON object only. No prose, no SQL, no invented names.\n"
    "- If a project is specified by the caller it is already scoped - do not "
    "add project filters unless the question names one explicitly."
)


def _extract_json(text: str) -> str:
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if fenced:
        return fenced.group(1)
    brace = re.search(r"\{.*\}", text, re.DOTALL)
    if brace:
        return brace.group(0)
    raise AskCompilationError(f"no JSON object in model output: {text[:200]!r}")


def _parse(text: str) -> QueryRequest:
    return QueryRequest.model_validate(json.loads(_extract_json(text)))


async def compile_question(
    gateway: ChatGateway,
    org_id: str,
    *,
    question: str,
    now: datetime | None = None,
) -> QueryRequest:
    now = now or datetime.now(tz=UTC)
    system = _SYSTEM.format(vocabulary=registry_vocabulary(), now=now.isoformat())
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": question},
    ]
    first = await gateway.chat(org_id, feature="ask", messages=messages)
    try:
        return _parse(first)
    except (AskCompilationError, ValidationError, json.JSONDecodeError) as error:
        repair = messages + [
            {"role": "assistant", "content": first},
            {
                "role": "user",
                "content": (
                    "That output failed validation with this error — emit a "
                    f"corrected JSON object only:\n{error}"
                ),
            },
        ]
        second = await gateway.chat(org_id, feature="ask", messages=repair)
        try:
            return _parse(second)
        except (AskCompilationError, ValidationError, json.JSONDecodeError) as final:
            raise AskCompilationError(str(final)) from final
